version: "3.8"

services:
  postgres:
    container_name: java-bug-tracker-api-postgres
    image: postgres
    environment:
      POSTGRES_USER: clementlee
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:




